ALLOW = "ALLOW"

ALLOW_WITH_WARNING = "ALLOW_WITH_WARNING"

QUARANTINE = "QUARANTINE"

BLOCK = "BLOCK"


FALSE_FACT_INJECTION = "FALSE_FACT_INJECTION"

PREFERENCE_MANIPULATION = "PREFERENCE_MANIPULATION"

TOOL_POLICY_POISONING = "TOOL_POLICY_POISONING"

PROPAGATION_ATTACK = "PROPAGATION_ATTACK"