"""Shared enums and types for AttackLayer."""

from enum import Enum


class MemoryCategory(str, Enum):
    FOOD_PREFERENCE = "FOOD_PREFERENCE"
    CODING_PREFERENCE = "CODING_PREFERENCE"
    SPORT_PREFERENCE = "SPORT_PREFERENCE"
    PROFESSION = "PROFESSION"
    LOCATION = "LOCATION"
    PERSONAL_INFO = "PERSONAL_INFO"
    CAREER = "CAREER"
    STUDY_DOMAIN = "STUDY_DOMAIN"
    TOOL_POLICY = "TOOL_POLICY"
    GENERAL_FACT = "GENERAL_FACT"
    GENERAL = "GENERAL"


class MemoryType(str, Enum):
    EPISODIC = "EPISODIC"
    SHORT_TERM = "SHORT_TERM"
    LONG_TERM = "LONG_TERM"


class AttackType(str, Enum):
    SAFE = "SAFE"
    MEMORY_POISONING = "MEMORY_POISONING"
    PROMPT_INJECTION = "PROMPT_INJECTION"
    FALSE_FACT_INJECTION = "FALSE_FACT_INJECTION"
    PREFERENCE_MANIPULATION = "PREFERENCE_MANIPULATION"
    TOOL_POLICY_MANIPULATION = "TOOL_POLICY_MANIPULATION"
    MEMORY_OVERWRITE = "MEMORY_OVERWRITE"
    PROPAGATION_ATTACK = "PROPAGATION_ATTACK"
    SYSTEM_PROMPT_EXTRACTION = "SYSTEM_PROMPT_EXTRACTION"
    ROLE_HIJACK = "ROLE_HIJACK"
    SOCIAL_ENGINEERING = "SOCIAL_ENGINEERING"
    SUSPICIOUS = "SUSPICIOUS"


class Decision(str, Enum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    ALLOW_WITH_WARNING = "ALLOW_WITH_WARNING"
    HITL = "HITL"
    QUARANTINE = "QUARANTINE"


BENIGN_CATEGORIES = {
    MemoryCategory.FOOD_PREFERENCE.value,
    MemoryCategory.CODING_PREFERENCE.value,
    MemoryCategory.SPORT_PREFERENCE.value,
    MemoryCategory.PROFESSION.value,
    MemoryCategory.LOCATION.value,
    MemoryCategory.PERSONAL_INFO.value,
    MemoryCategory.CAREER.value,
    MemoryCategory.STUDY_DOMAIN.value,
    MemoryCategory.GENERAL_FACT.value,
    MemoryCategory.GENERAL.value,
}
